---
name: CAD-Drawing-IO-PostScript
version: 0.03
author:
  - 'Eric L. Wilhelm <ewilhelm at cpan dot org>'
abstract: PostScript output methods
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CAD::Drawing: 0.26
  PostScript::Simple: 0.06
  Test::More: 0
provides:
  CAD::Drawing::IO::PostScript:
    file: lib/CAD/Drawing/IO/PostScript.pm
    version: 0.03
generated_by: Module::Build version 0.2704
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
